name: Get new bangs
on:
    workflow_dispatch:
    schedule: 
        - cron: "0 0 * * *"
jobs:
    Download-ddg-bangs:
        runs-on: ubuntu-latest
        outputs:
            new-bangs: ${{ steps.new-bangs.outcome }}
        steps:
            - uses: actions/checkout@v4
            - name: Fetch latest bangs
              run: curl https://duckduckgo.com/bang.js -O
            - name: Get last bangs version from cache
              id: get-cached-bangs
              uses: actions/cache@v4
              with:
                key: latest-bangs.js
                path: latest-bangs.js
            - name: Compare versions
              if: steps.get-cached-bangs.cache-hit == 'success'
              id: compare-bangs
              run: diff -sq latest-bangs.js bang.js > /dev/null
              continue-on-error: true
            - name: Upload new bangs
              if: steps.compare-bangs.outcome == 'failure'
              id: new-bangs
              run: 'mv -f bang.js latest-bangs.js'